# Generated by Django 5.2 on 2025-04-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_appointment_description_appointment_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
